# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Pessoal\Desktop\qt\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox
)
from PyQt5.uic import loadUi

from PyQt5 import _QOpenGLFunctions_2_0

from OpenGL.GL import *
from OpenGL.GLU import *
from OpenGL.GLUT import *



class Canvas(QtWidgets.QOpenGLWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        
    
    def mousePressEvent(self, a0: QtGui.QMouseEvent) -> None:
        print("CJAHSJDHJAQs")
        print(a0.pos())
        return super().mousePressEvent(a0)

    def initializeGL(self) -> None:
        glClearColor(0.8, 0.7, 0.2, 1.0)
        f = _QOpenGLFunctions_2_0.QOpenGLFunctions_2_0
        print('initialize')
        return super().initializeGL()
    
    def paintGL(self) -> None:
        glBegin(GL_LINES)
        glVertex3f(-1, -1, 0.0)
        glVertex3f(1, 0.5, 0.0)
        glEnd()
        return super().paintGL()
    
    def resizeGL(self, w: int, h: int) -> None:
        print('resizae')
        return super().resizeGL(w, h)
    


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = Canvas(self.centralwidget)#QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(130, 20, 491, 281))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 330, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def onCanvasClick(self):
        print('asdasd')

    def drawBtnClick(self):
        print('click')
        self.openGLWidget.makeCurrent()
        glClearColor(0.5, 0.1, 1.0, 1.0)
        glBegin(GL_LINES)
        glVertex2f(0,0)
        glVertex2f(100,100)
        glEnd()
        self.openGLWidget.update()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Desenhar"))
        self.pushButton.clicked.connect(self.drawBtnClick)


class Window(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

app = QApplication(sys.argv)
win = Window()
win.show()
sys.exit(app.exec())
