# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


from canvas import Canvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.modo_livre_activated = False

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = Canvas(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 10, 601, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 410, 111, 31))
#         self.pushButton.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 360, 731, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 450, 111, 31))
#         self.pushButton_3.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 430, 111, 31))
#         self.pushButton_4.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 380, 141, 31))
        self.label.setStyleSheet("font-size: 16px;\n"
"font-family: Perpetua, Serif;\n"
"font-weight:700;")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 610, 41, 31))
#         self.pushButton_5.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        self.pushButton_5.setObjectName("pushButton_5")
#         self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_6.setGeometry(QtCore.QRect(490, 650, 41, 31))
# #         self.pushButton_6.setStyleSheet("border: 2px solid #731;\n"
# # "border-radius: 7px;\n"
# # "background-color: #E2E2E2;\n"
# # "font-size: 13px;\n"
# # "font-family: Perpetua, Serif;\n"
# # "font-weight:700;")
#         self.pushButton_6.setObjectName("pushButton_6")
#         self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_7.setGeometry(QtCore.QRect(490, 570, 41, 31))
# #         self.pushButton_7.setStyleSheet("border: 2px solid #731;\n"
# # "border-radius: 7px;\n"
# # "background-color: #E2E2E2;\n"
# # "font-size: 13px;\n"
# # "font-family: Perpetua, Serif;\n"
# # "font-weight:700;")
#         self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 610, 41, 31))
#         self.pushButton_8.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 530, 101, 31))
        self.label_2.setStyleSheet("font-size: 16px;\n"
"font-family: Perpetua, Serif;\n"
"font-weight:700;")
        self.label_2.setObjectName("label_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 490, 111, 31))
#         self.pushButton_9.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
#         self.pushButton_9.setObjectName("pushButton_9")
#         self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
#         self.lineEdit.setGeometry(QtCore.QRect(20, 610, 161, 31))
#         self.lineEdit.setStyleSheet("font-size: 16px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        # self.lineEdit.setObjectName("lineEdit")
        # self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_10.setGeometry(QtCore.QRect(190, 610, 131, 31))
#         self.pushButton_10.setStyleSheet("border: 2px solid #731;\n"
# "border-radius: 7px;\n"
# "background-color: #E2E2E2;\n"
# "font-size: 13px;\n"
# "font-family: Perpetua, Serif;\n"
# "font-weight:700;")
        #self.pushButton_10.setObjectName("pushButton_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton.clicked.connect(self.openGLWidget.add_quad)
        self.pushButton_3.clicked.connect(self.openGLWidget.add_triangle)
        self.pushButton_4.clicked.connect(self.modo_livre_click)
        self.pushButton_9.clicked.connect(self.limpar)
        self.pushButton_5.clicked.connect(self.rotate_left)
        self.pushButton_8.clicked.connect(self.rotate_right)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def limpar(self):
        self.openGLWidget.limpar()

    def rotate_left(self):
        self.openGLWidget.rotate(5)

    def rotate_right(self):
        self.openGLWidget.rotate(-5)

    def modo_livre_click(self):
        self.modo_livre_activated = not self.modo_livre_activated
        if self.modo_livre_activated:
                self.pushButton_4.setText(QtCore.QCoreApplication.translate("MainWindow", "Pronto"))
                self.openGLWidget.ativar_modo_livre()
        else:
                self.pushButton_4.setText(QtCore.QCoreApplication.translate("MainWindow", "Modo Livre"))
                self.openGLWidget.desativar_modo_livre()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Quadrilatero"))
        self.pushButton_3.setText(_translate("MainWindow", "Triangulo"))
        self.pushButton_4.setText(_translate("MainWindow", "Modo Livre"))
        self.label.setText(_translate("MainWindow", "Adicionar:"))
        self.pushButton_5.setText(_translate("MainWindow", "˂"))
        #self.pushButton_6.setText(_translate("MainWindow", "˅"))
        #self.pushButton_7.setText(_translate("MainWindow", "˄"))
        self.pushButton_8.setText(_translate("MainWindow", "˃"))
        self.label_2.setText(_translate("MainWindow", "Rotacionar"))
        self.pushButton_9.setText(_translate("MainWindow", "LIMPAR"))
        #self.pushButton_10.setText(_translate("MainWindow", "Definir Background"))



